### ISSUE TITLE
Crash after "Close" on E-500, E-550

### ISSUE THREAD

**Issue by romanpohl** [pockemul/PockEmul#16]
Steps to reproduce:
1) Start PockEmul
2) Main menu -> Session -> New... -> double click on the E-500 or E-550.
3) Right click on the computer image -> Close
4) Program crashes.

Oddly enough, if the E-500 is selected from the carousel, Close on it will not crash. And if the E-550 is selected from the carousel, Close on it will sometimes crash and sometimes not crash.

PockEmul 1.0.1-beta
Windows 7 Pro 64-bit

**Comment by prosiak** [comment]
Still crashes sometimes when turning it ON (not OFF but ON). Sometimes when i do reset it does not crashes.
And the printer seems to not work with those models.
