### ISSUE TITLE
[GUI] Long click to open context menu drags object when leaving menu

### ISSUE THREAD

**Issue by mvcube** [pockemul/PockEmul#23]
The problem seems to be that the long click/tap doubles as start drag and open menu. I've seen this on OS-X and Android. It should be present on iOS as well.

Marcus

**Comment by pockemul** [comment]
Seems to be fixed in 1.4 on Windows.

**Comment by pockemul** [comment]
The context menu is shown on double clik. Long tap is not managed anymore.
