### ISSUE TITLE
pockemul on nexus 7/2012

### ISSUE THREAD

**Issue by Charios01** [pockemul/PockEmul#84]
Hi,
can't get pockemul to work on my nexus 7/Mod. 3568A-ME370T, Android 4.2.2, Kernel 3.1.10-gb05b777c. After starting I see usual start screen, then 'loading modules screen, then white screen. No menu button, no reaction to back butto. Can put it to background and close it from there. Deleting cache/date didn't help. Tried 1.4.3 and also 1.4.2.
Klaus

**Comment by pockemul** [comment]
Pockemul  1.5.0 need Android >= 5.0

Just after 1.5 release, i will investigate to enhence compatibility to prior Android version.

**Comment by pockemul** [comment]
duplicate #142
