### ISSUE TITLE
[PB-2000C] Android EXE key not working

### ISSUE THREAD

**Issue by iardsoft** [pockemul/PockEmul#95]
Tried on two different Android tablets, with different screen resolution.
Stuck at Memory initialize OK? (EXE key).
EXE key produces feedback, but doesn't have any effect.
Changing ROM modules changes the keyboard overlay, for instance from C to BASIC, but can't go any further than initialize memory.
Windows version works fine, I think it's just something to do with Android. Tried moving the EXE button around, and resizing it, but no effect.

**Comment by pockemul** [comment]
Hi,
Pockemul try to mimic exactly the real life. 
Sometimes, i must admit, it's too much.

The first time you start the PB-200C, you have to reset it properly.
Turn the pocket back (by slicing, or clicking on the edges (see parameters)) ans click on RESET and NEW ALL keys.
It will initialize correctly the pocket.

regards

**Comment by iardsoft** [comment]
Thank you for your response! If only it would be that easy... I tried the Reset / NewAll combination before opening this issue.

Meanwhile I also installed the NoxPlayer Android emulator on Win10 to test if this works on a new install, without having to reset my tablets to factory. No luck, same thing happens. Same if I install 1.4.2 apk.

If I transfer to Android and load the pb2000.pkm that works on the Windows version, the screen is like in the attached screenshot, two empty menus. None of the keys work. Reset/NewAll just returns the calculator to the Memory initialize step.

Thank you again!
![capture](https://user-images.githubusercontent.com/45291526/52168502-d876f200-2733-11e9-9ea0-003e1afe8612.JPG)

**Comment by pockemul** [comment]
I just tried on my Android phone (android 8.1)
A fresh install of my dev release (1.5.0).
When i start the PB-2000C, i have exactly the same screen with the two empty menus and the cursor blinking at the top left corner.
I turn back the pocket (keeping the power on) and click on RESET for 3 seconds, then NEW ALL for 3 Seconds.
Then if i turn it back, it works.

I will try the 1.4.3

**Comment by iardsoft** [comment]
Both my tablets run Android 7.0, and the NoxPlayer emulator 4.4.2
Don't know if this is an issue, but all 3 are rooted...

1.4.3 installs on my phone, a BlackBerry Key One running Android 8.1 (not rooted), but with the same problem for PB-2000C.

**Comment by pockemul** [comment]
It is very strange that i cannot install 1.4.3 on my android 8.1 phone...
in the meantime, if you send me an email to pockemul@free.fr i will provide you a link to download the current dev 1.5.0
I haven't test it on android 7 but it should work.

**Comment by pockemul** [comment]
I make some progress.
In fact PB-2000C keyboard isn't working on 32bit package.
With the 64bit package, it works.
So, the bug is in the core emulation. Perhaps a miss-alignment in memory variable storage or an Endianness issue.
